version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - mailhog
    command: ["/wait-for-it.sh", "db:5432", "--", "node", "src/server.js"]

  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ctfdb
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  postgres_data:
  node_modules:
